-- The whole library. Every module is imported here, so `lake build` checks all of
-- it: the lean_lib declares no `globs`, and therefore this root module is the only
-- build target.
--
-- The one exclusion is `Adic spaces/Comparator/`. `Challenge.lean` and
-- `WPChallenge.lean` state the certified theorems with `sorry` proofs by design --
-- they are the pinned statements comparator judges the solutions against -- so they
-- must stay out of the default build. `scripts/certify.sh` builds them by name.
import «Adic spaces».AdicCompletionBridge
import «Adic spaces».AdicCompletionFaithfullyFlat
import «Adic spaces».AdicCompletionNoetherian
import «Adic spaces».AdicCompletionTransfer
import «Adic spaces».AdicConvergence
import «Adic spaces».AdicMorphisms
import «Adic spaces».AdicMorphismsCore
import «Adic spaces».AdicNakayama
import «Adic spaces».AdicSpaceMorphisms
import «Adic spaces».AdicSpectrum
import «Adic spaces».AffinoidRings
import «Adic spaces».AffinoidTransport
import «Adic spaces».AlmostMathematics
import «Adic spaces».AnalyticPoints
import «Adic spaces».ArtinReesConvergence
import «Adic spaces».AuditCleanWrappers
import «Adic spaces».BanachOMT
import «Adic spaces».Basic
import «Adic spaces».BivariateContinuity
import «Adic spaces».Bounded
import «Adic spaces».CechAcyclicityFull
import «Adic spaces».CechCohomology
import «Adic spaces».CechRationalCover
import «Adic spaces».CechRefinementCalculus
import «Adic spaces».CharacteristicSubgroup
import «Adic spaces».CoherentRing
import «Adic spaces».CompleteTopCommRingCat
import «Adic spaces».CompletedAlgClosure
import «Adic spaces».CompletedResidueField
import «Adic spaces».CompletionExact
import «Adic spaces».CompletionLocalization
import «Adic spaces».CompletionModelIndependence
import «Adic spaces».ContinuousValuations
import «Adic spaces».Cor732
import «Adic spaces».Cor832
import «Adic spaces».CornerSquareDatum
import «Adic spaces».EmbeddingTopo
import «Adic spaces».Example638
import «Adic spaces».ExampleLaurentSeries
import «Adic spaces».ExampleUnitDisc
import «Adic spaces».ExcellentRing
import «Adic spaces».FJP.AdicCompletionPrincipal
import «Adic spaces».FJP.CDVFBase
import «Adic spaces».FJP.CDVFDichotomy
import «Adic spaces».FJP.CDVFNoetherian
import «Adic spaces».FJP.CornerSquareBridge
import «Adic spaces».FJP.CornerSquareLocalization
import «Adic spaces».FJP.ExtendedCornerPackage
import «Adic spaces».FJP.ExtendedMilnorInstance
import «Adic spaces».FJP.ExtendedSheafyTransport
import «Adic spaces».FJP.FiniteJetChart
import «Adic spaces».FJP.FiniteJetFunctoriality
import «Adic spaces».FJP.FiniteJetGraphKoszul
import «Adic spaces».FJP.FiniteJetMain
import «Adic spaces».FJP.FiniteJetNoetherianVertices
import «Adic spaces».FJP.FiniteJetRings
import «Adic spaces».FJP.FiniteJetSheafTransfer
import «Adic spaces».FJP.FiniteJetSheafyEndpoints
import «Adic spaces».FJP.FiniteJetStrictLocalization
import «Adic spaces».FJP.FiniteJetUniformDomain
import «Adic spaces».FJP.KoszulFiniteFree
import «Adic spaces».FJP.KoszulFreeExactness
import «Adic spaces».FJP.KoszulRestrictedExactness
import «Adic spaces».FJP.KoszulStrictClosed
import «Adic spaces».FJP.Milnor.StrictMilnorSquare
import «Adic spaces».FJP.MilnorSquareInstance
import «Adic spaces».FJP.Over.Chart
import «Adic spaces».FJP.Over.ExamplePadic
import «Adic spaces».FJP.Over.ExtendedCornerPackage
import «Adic spaces».FJP.Over.ExtendedMilnorInstance
import «Adic spaces».FJP.Over.ExtendedSheafyTransport
import «Adic spaces».FJP.Over.Functoriality
import «Adic spaces».FJP.Over.JetRings
import «Adic spaces».FJP.Over.LaurentCompat
import «Adic spaces».FJP.Over.SheafTransfer
import «Adic spaces».FJP.Over.SheafyEndpoints
import «Adic spaces».FJP.Over.StrictLocalization
import «Adic spaces».FJP.Over.StrongSheafy
import «Adic spaces».FJP.Over.TateInstances
import «Adic spaces».FJP.Over.UniformDomain
import «Adic spaces».FJP.QuotientPowFlat
import «Adic spaces».FJP.RestrictedFubini
import «Adic spaces».FJP.RestrictedGaussAdic
import «Adic spaces».FJP.RestrictedLaurent
import «Adic spaces».FJP.RestrictedTruncation
import «Adic spaces».FJP.SpectralExtension
import «Adic spaces».FJP.StrongSheafy
import «Adic spaces».FJP.TateBallResidue
import «Adic spaces».FJP.TateNullstellensatz
import «Adic spaces».FJP.TatePointEval
import «Adic spaces».FJP.TateReducedLocal
import «Adic spaces».FJP.TateScalarExtension
import «Adic spaces».FJP.TateTaylor
import «Adic spaces».FJP.TateWallFactors
import «Adic spaces».FaithfulLocLift
import «Adic spaces».FarguesFontaine
import «Adic spaces».FlatCompletion
import «Adic spaces».FlatnessResults
import «Adic spaces».GeometricReduction
import «Adic spaces».GeometricSeries
import «Adic spaces».HomSheafPredicate
import «Adic spaces».HuberLocLift
import «Adic spaces».HuberRings
import «Adic spaces».HubnerSeparation
import «Adic spaces».IdealClosedness
import «Adic spaces».IdealLocalization
import «Adic spaces».IdealLocalizationCompletion
import «Adic spaces».IntegralStructureSheaf
import «Adic spaces».IteratedOverlapEquiv
import «Adic spaces».IteratedRational
import «Adic spaces».JetDualNumberNorm
import «Adic spaces».LaneAReverseRoundTrip
import «Adic spaces».LaurentBaireSupport
import «Adic spaces».LaurentCoverExact
import «Adic spaces».LaurentCoverTopology
import «Adic spaces».LaurentMinusNormalized
import «Adic spaces».LaurentOverlap
import «Adic spaces».LaurentOverlapConsumer
import «Adic spaces».LaurentRefinement
import «Adic spaces».LaurentRefinementAcyclic
import «Adic spaces».LaurentRefinementCore
import «Adic spaces».LaurentRefinementTree
import «Adic spaces».LaurentSeparationPresheaf
import «Adic spaces».LeafAChainAssembly
import «Adic spaces».Lemma745
import «Adic spaces».LocalBasis
import «Adic spaces».LocalizationTopology
import «Adic spaces».MilnorSheafTransfer
import «Adic spaces».MvTateAlgebraTopology
import «Adic spaces».NoetherianGDomain
import «Adic spaces».NoetherianTateModules
import «Adic spaces».OpenIdeals
import «Adic spaces».OpenMapping
import «Adic spaces».OrderedGroupConvex
import «Adic spaces».PerfectoidRing
import «Adic spaces».PerfectoidSpace
import «Adic spaces».Presheaf
import «Adic spaces».PresheafAdicCompletion
import «Adic spaces».PresheafFunctoriality
import «Adic spaces».PresheafIdentification
import «Adic spaces».PresheafTateStructure
import «Adic spaces».Prop752
import «Adic spaces».PseudoUniformizer
import «Adic spaces».QuotientTate
import «Adic spaces».RationalBasis
import «Adic spaces».RationalIntersection
import «Adic spaces».RationalRefinement
import «Adic spaces».RationalSubsets
import «Adic spaces».RationalTransitivity
import «Adic spaces».RelativeDescent
import «Adic spaces».RelativePieceKeystone
import «Adic spaces».RelativeRationalLocData
import «Adic spaces».RelativeStandardRefinement
import «Adic spaces».RestrictedModule
import «Adic spaces».RestrictedPowerSeries
import «Adic spaces».RestrictionFlatness
import «Adic spaces».RingEquivPresheafTransport
import «Adic spaces».ScottishBook.Described.Problem011
import «Adic spaces».ScottishBook.Described.Problem016
import «Adic spaces».ScottishBook.Described.Problem018
import «Adic spaces».ScottishBook.Described.Problem040
import «Adic spaces».ScottishBook.Stated.Problem001
import «Adic spaces».ScottishBook.Stated.Problem002
import «Adic spaces».ScottishBook.Stated.Problem003
import «Adic spaces».ScottishBook.Stated.Problem004
import «Adic spaces».ScottishBook.Stated.Problem005
import «Adic spaces».ScottishBook.Stated.Problem006
import «Adic spaces».ScottishBook.Stated.Problem007
import «Adic spaces».ScottishBook.Stated.Problem008
import «Adic spaces».ScottishBook.Stated.Problem009
import «Adic spaces».ScottishBook.Stated.Problem010
import «Adic spaces».ScottishBook.Stated.Problem012
import «Adic spaces».ScottishBook.Stated.Problem013
import «Adic spaces».ScottishBook.Stated.Problem014
import «Adic spaces».ScottishBook.Stated.Problem015
import «Adic spaces».ScottishBook.Stated.Problem017
import «Adic spaces».ScottishBook.Stated.Problem019
import «Adic spaces».ScottishBook.Stated.Problem020
import «Adic spaces».ScottishBook.Stated.Problem021
import «Adic spaces».ScottishBook.Stated.Problem022
import «Adic spaces».ScottishBook.Stated.Problem023
import «Adic spaces».ScottishBook.Stated.Problem024
import «Adic spaces».ScottishBook.Stated.Problem025
import «Adic spaces».ScottishBook.Stated.Problem026
import «Adic spaces».ScottishBook.Stated.Problem027
import «Adic spaces».ScottishBook.Stated.Problem028
import «Adic spaces».ScottishBook.Stated.Problem029
import «Adic spaces».ScottishBook.Stated.Problem030
import «Adic spaces».ScottishBook.Stated.Problem031
import «Adic spaces».ScottishBook.Stated.Problem032
import «Adic spaces».ScottishBook.Stated.Problem033
import «Adic spaces».ScottishBook.Stated.Problem034
import «Adic spaces».ScottishBook.Stated.Problem035
import «Adic spaces».ScottishBook.Stated.Problem036
import «Adic spaces».ScottishBook.Stated.Problem037
import «Adic spaces».ScottishBook.Stated.Problem038
import «Adic spaces».ScottishBook.Stated.Problem039
import «Adic spaces».SemilocalFibre
import «Adic spaces».SeminormalRing
import «Adic spaces».SheafyCompletionModel
import «Adic spaces».SheafyEndpoints
import «Adic spaces».SheafyFoundations
import «Adic spaces».SheafyPair
import «Adic spaces».SheafyRing
import «Adic spaces».SheafyRingEquivTransport
import «Adic spaces».SpaCompact
import «Adic spaces».SpaCompactNoHArch
import «Adic spaces».SpaParameterPerturbation
import «Adic spaces».SpaQCviaSpvAI
import «Adic spaces».SpaRationalOpenComparison
import «Adic spaces».SpaRationalOpenHomeomorph
import «Adic spaces».SpaRationalSubsetCorrespondence
import «Adic spaces».SpaSpanPerturbation
import «Adic spaces».SpvAI
import «Adic spaces».SpvAITopology
import «Adic spaces».SpvCompletionExtension
import «Adic spaces».StandardCover
import «Adic spaces».StandardCoverConditionalBridge
import «Adic spaces».StandardDescent
import «Adic spaces».StandardRefinement
import «Adic spaces».StronglyNoetherianTransport
import «Adic spaces».StructurePresheafBundled
import «Adic spaces».StructurePresheafLimit
import «Adic spaces».StructureSheaf
import «Adic spaces».TateAcyclicity
import «Adic spaces».TateAcyclicityFinalAssembly
import «Adic spaces».TateAcyclicityResiduals
import «Adic spaces».TateAlgebra
import «Adic spaces».TateAlgebraTopology
import «Adic spaces».TateAlgebraWedhorn
import «Adic spaces».Tilting
import «Adic spaces».TopologyComparison
import «Adic spaces».Uniform
import «Adic spaces».UniformBanach
import «Adic spaces».ValuationAction
import «Adic spaces».ValuationCoarsening
import «Adic spaces».ValuationContinuity
import «Adic spaces».ValuationPrimeConvex
import «Adic spaces».ValuationSpectrum
import «Adic spaces».ValuationSpectrumCompact
import «Adic spaces».ValuativeRel.Comap
import «Adic spaces».Vendored.CoramMvGaussNorm
import «Adic spaces».Vendored.CoramMvRestricted
import «Adic spaces».Vendored.CoramMvRestrictedNorm
import «Adic spaces».Vendored.CoramRestrictedCore
import «Adic spaces».Vendored.CoramRestrictedIso
import «Adic spaces».Vendored.CoramRestrictedNorm
import «Adic spaces».Vendored.XiaMvPowerSeriesEquiv
import «Adic spaces».WP.Algebra
import «Adic spaces».WP.ChainReducedDef
import «Adic spaces».WP.Chart
import «Adic spaces».WP.CoeffLocalization
import «Adic spaces».WP.CompletedLocalTransport
import «Adic spaces».WP.Evaluation
import «Adic spaces».WP.FormalReduced
import «Adic spaces».WP.GraphCompletedLocal
import «Adic spaces».WP.GraphFibreBeta
import «Adic spaces».WP.GraphFibreL1
import «Adic spaces».WP.GraphFlat
import «Adic spaces».WP.HeadAwayW
import «Adic spaces».WP.HeadReduced
import «Adic spaces».WP.HeadReducedMaximal
import «Adic spaces».WP.HeadReducedNotMem
import «Adic spaces».WP.HeadTResidue
import «Adic spaces».WP.Heads
import «Adic spaces».WP.KappaResidue
import «Adic spaces».WP.Main
import «Adic spaces».WP.Nonnoetherian
import «Adic spaces».WP.Perturbation
import «Adic spaces».WP.Reduced
import «Adic spaces».WP.RestrictedComplete
import «Adic spaces».WP.Sheafy
import «Adic spaces».WP.StrongSheafy
import «Adic spaces».WP.Tail
import «Adic spaces».WP.UniformDomain
import «Adic spaces».WP.Weight
import «Adic spaces».WP.ZeroHeadTate
import «Adic spaces».Wedhorn745PointwiseBaseRefinementDischarge
import «Adic spaces».Wedhorn828
import «Adic spaces».Wedhorn834C1SupplierLocalInterface
import «Adic spaces».WedhornActualC1PerCallClosure
import «Adic spaces».WedhornAlphaTDComparisonSupplier
import «Adic spaces».WedhornAwayMapSaturation
import «Adic spaces».WedhornBanachTheorem
import «Adic spaces».WedhornBaseRationalComapResidualDischarge
import «Adic spaces».WedhornC1Assembly
import «Adic spaces».WedhornC1AssemblyStrong
import «Adic spaces».WedhornC1ComapLiftRestrictedSupplier
import «Adic spaces».WedhornC1CoverAssemblyClosure
import «Adic spaces».WedhornC1CoverPieceStructuralAssembly
import «Adic spaces».WedhornC1PerCallSupplyHonest
import «Adic spaces».WedhornC1PerCallSupplyHonestAssembly
import «Adic spaces».WedhornC1PerWCoverPieceSupplier
import «Adic spaces».WedhornC1SigmaConstructionAssembly
import «Adic spaces».WedhornC1SigmaImageAlignment
import «Adic spaces».WedhornC1StrongSupplierBridge
import «Adic spaces».WedhornC1StrongSupplierCore
import «Adic spaces».WedhornC1SupplierLaurentAssembly
import «Adic spaces».WedhornCechAcyclicity
import «Adic spaces».WedhornCompactExtraction
import «Adic spaces».WedhornCor732BranchTransfer
import «Adic spaces».WedhornCor732ChainIdentityFromLocalizedOutput
import «Adic spaces».WedhornCor732DirectUpperBoundResidual
import «Adic spaces».WedhornCor732PerTauUpperBoundResidual
import «Adic spaces».WedhornCovPlusLiftPerTBoundDischarge
import «Adic spaces».WedhornCoverNormalization
import «Adic spaces».WedhornCoverPieceLocRationalBoundDischarge
import «Adic spaces».WedhornCoverPieceRationalBoundInterface
import «Adic spaces».WedhornCoverPieceStructuralData
import «Adic spaces».WedhornCoverPieceStructuralDataDischarge
import «Adic spaces».WedhornDenominatorClearedCandidate
import «Adic spaces».WedhornDirectUpperBoundSupplierFromPointwiseClearing
import «Adic spaces».WedhornDominatingBranchInequality
import «Adic spaces».WedhornDominatingUnitInequality
import «Adic spaces».WedhornExtendValuationContinuity
import «Adic spaces».WedhornFactorExtractionPowerDecay
import «Adic spaces».WedhornFullLaurentAlphaTDBranch
import «Adic spaces».WedhornFullLaurentLowerBranchBound
import «Adic spaces».WedhornFullLaurentVKBranchDecomposition
import «Adic spaces».WedhornLaurentLocalBoundsFromCor732
import «Adic spaces».WedhornLaurentPieceCor732RationalOpenData
import «Adic spaces».WedhornLaurentPieceFactoredChain
import «Adic spaces».WedhornLaurentProductBoundSupplier
import «Adic spaces».WedhornLocTopologyLinear
import «Adic spaces».WedhornLocalArithmeticPerTChain
import «Adic spaces».WedhornLocalCompatFromTestFamily
import «Adic spaces».WedhornLocalCor732ToFactoredChain
import «Adic spaces».WedhornLocalPerBranchChain
import «Adic spaces».WedhornLocalSubsetViaFactoredChains
import «Adic spaces».WedhornLocalizationContinuity
import «Adic spaces».WedhornLocalizationDenominatorClearing
import «Adic spaces».WedhornLocalizationDenominatorUnit
import «Adic spaces».WedhornLocalizationLiftContinuity
import «Adic spaces».WedhornLocalizationLiftContinuityBounded
import «Adic spaces».WedhornLocalizationPlus
import «Adic spaces».WedhornLocalizationTransferConsumer
import «Adic spaces».WedhornLocalizedArchimedeanTransfer
import «Adic spaces».WedhornLocalizedCor732Application
import «Adic spaces».WedhornLocalizedCor732Bridge
import «Adic spaces».WedhornLocalizedCor732Consumer
import «Adic spaces».WedhornLocalizedCor732SigmaSupplier
import «Adic spaces».WedhornLocalizedMultiPieceLaurentRefinement
import «Adic spaces».WedhornLocalizedTateData
import «Adic spaces».WedhornMPowerDecayFromStructural
import «Adic spaces».WedhornMPowerStructuralDataHonest
import «Adic spaces».WedhornMPowerStructuralDataHonestFromCor732
import «Adic spaces».WedhornMPowerStructuralDataHonestFromLaurentPiece
import «Adic spaces».WedhornMaxElementSDComparison
import «Adic spaces».WedhornMultiBranchSubsetInequality
import «Adic spaces».WedhornMultiDominatingUnit
import «Adic spaces».WedhornMultiPieceLaurentRefinement
import «Adic spaces».WedhornNormalizedC1Assembly
import «Adic spaces».WedhornNormalizedC1AssemblyStrong
import «Adic spaces».WedhornOutsideRescue
import «Adic spaces».WedhornPerPieceLaurentC1Supplier
import «Adic spaces».WedhornPerPieceLaurentCoverAssembly
import «Adic spaces».WedhornPerPieceSubsetAdapterFromT056
import «Adic spaces».WedhornPerPieceSubsetProductClearing
import «Adic spaces».WedhornPerTFactoredBranchLink
import «Adic spaces».WedhornPerWCoverPieceUpperBound
import «Adic spaces».WedhornPointwiseClearingFromLocalizedCor732
import «Adic spaces».WedhornPointwiseClearingSupplierFromSigmaPower
import «Adic spaces».WedhornPointwiseSigmaProductClearing
import «Adic spaces».WedhornPrelocalizationTransfer
import «Adic spaces».WedhornRationalOpenLocalizationTransfer
import «Adic spaces».WedhornSigmaDominationClearing
import «Adic spaces».WedhornSigmaFactoredInequalityAtCor732Sigma
import «Adic spaces».WedhornSigmaFactoredSupplierFromLocalizedCor732
import «Adic spaces».WedhornSigmaPowerClearedInequalitySupplier
import «Adic spaces».WedhornSigmaPowerDecay
import «Adic spaces».WedhornSigmaPowerInequalityFromLocalizedCor732
import «Adic spaces».WedhornSourceLaurentMembershipInLocalizationBase
import «Adic spaces».WedhornSourceSigmaDecayFromLocalizedChain
import «Adic spaces».WedhornSpaRationalOpenLiftWrapper
import «Adic spaces».WedhornStandardCoverRefinement
import «Adic spaces».WedhornStrengthenedC1
import «Adic spaces».WedhornStrengthenedCompactExtraction
import «Adic spaces».WedhornStronglyNoetherian
import «Adic spaces».WedhornStructuralInequalityFromSigmaPower
import «Adic spaces».WedhornTateAcyclicityFinalClosure
import «Adic spaces».WedhornVKMaxElementComparisonDischarge
import «Adic spaces».WedhornVKNonemptyPerTBoundDischarge
import «Adic spaces».WedhornVKNonemptyRationalBoundDischarge
import «Adic spaces».WedhornValuationLocalizationLift
import «Adic spaces».WedhornValueGroupLocalizationStrictMono
import «Adic spaces».WittVectorPrimitive
