#!/usr/bin/env python3
"""Generate `Palomar/Defs.lean` from `Palomar/Challenge.lean`.

Comparator compares the Challenge's declarations with same-named declarations in the Solution's
environment, and the Solution must not import the Challenge (its `sorry`ed theorems would clash).
So the definitions the statements are about live in `Palomar/Defs.lean`, a verbatim copy of the
Challenge minus the statements section, which `Palomar/Bridge*.lean` and `Palomar/Solution.lean`
import. Same text + same imports => same elaborated constants, which is what Comparator checks.

`Palomar/Challenge.lean` is the hand-maintained source of truth; run this after editing it.
`--check` exits nonzero if `Defs.lean` is out of date.
"""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CH = os.path.join(ROOT, "Palomar", "Challenge.lean")
DEFS = os.path.join(ROOT, "Palomar", "Defs.lean")
MARK = "/-! ## 12. The statements"

def generate() -> str:
    src = open(CH, encoding="utf-8").read()
    i = src.index(MARK)
    head = src[:i].rstrip() + "\n\nend Palomar\n"
    head = head.replace(
        "# Palomar challenge: the two headline theorems, stated self-containedly",
        "# Palomar challenge — the definitions (GENERATED from `Palomar/Challenge.lean`)\n\n"
        "**Do not edit.** This file is `Palomar/Challenge.lean` minus its statements section,\n"
        "regenerated by `scripts/gen-defs.py`. It exists because Comparator's Solution module must\n"
        "contain the same definitions as the Challenge without importing the Challenge module.", 1)
    return head

def main() -> int:
    out = generate()
    if "--check" in sys.argv:
        cur = open(DEFS, encoding="utf-8").read() if os.path.exists(DEFS) else ""
        if cur != out:
            print("Palomar/Defs.lean is out of date; run scripts/gen-defs.py"); return 1
        print("Palomar/Defs.lean is up to date"); return 0
    open(DEFS, "w", encoding="utf-8").write(out)
    print(f"wrote {DEFS} ({len(out.splitlines())} lines)"); return 0

if __name__ == "__main__":
    sys.exit(main())
